name: Update Market Prices

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run bot every 1 minute
        run: |
          for i in {1..5}
          do
            echo "Run $i"
            python main.py
            sleep 60
          done
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
